stages:
  - test
  - bot # comes from translations/generator job

.before_script_mac: &before_script_mac
  - cd ProtonMail/ProtonMailUITests/ && sh Tests/TestPlans/scripts/prepare_users.sh && cd .. && cd ..


# --- includes ---
include:
  - project: 'translations/generator'
    ref: master
    file: '/jobs/sync-crowdin.gitlab-ci.yml'

  - project: 'translations/generator'
    ref: master
    file: '/jobs/commit-locales.gitlab-ci.yml'


variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GEM_HOME: "$CI_PROJECT_DIR/gem"

unit_tests:
   dependencies: []
   stage: test
   only:
    - master
    - develop
    - /^release\/.*$/
    - merge_requests
   before_script:
    - git config --global url."https://gitlab_deploy_token_mail:${CI_JOB_TOKEN_PMNETWORK}@gitlab.protontech.ch/apple/shared/pmnetworking".insteadOf git@gitlab.protontech.ch:apple/shared/pmnetworking
    - git submodule init
    - git submodule update --init --recursive 
    # - pip install xUnique
   script:
    - defaults write com.apple.iphonesimulator ConnectHardwareKeyboard 0 # Fixed UI tests failing on secure field
    - fastlane scan --workspace "ProtonMail/Protonmail.xcworkspace" --scheme "Tests" --device "iPhone 8" --clean
   tags:
    - iOS
    
ui_tests:
   dependencies: []
   stage: test
   artifacts:
    name: "test-report"
    paths:
      - ./test_output/report.html
      - ./test_output/report.junit
    expire_in: 20 days
    reports:
      junit: ./test_output/report.junit
   before_script:
    - *before_script_mac
    - git config --global url."https://gitlab_deploy_token_mail:${CI_JOB_TOKEN_PMNETWORK}@gitlab.protontech.ch/apple/shared/pmnetworking".insteadOf git@gitlab.protontech.ch:apple/shared/pmnetworking
    - git submodule init
    - git submodule update --init --recursive
   script:
    - defaults write com.apple.iphonesimulator ConnectHardwareKeyboard 0 # Fixed UI tests failing on secure field
    - fastlane scan --workspace "ProtonMail/Protonmail.xcworkspace" --scheme "ProtonMailUITests" --testplan "SmokeTests"  --device "iPhone 11" --clean
   tags:
    - iOS

# --- Translation related tasks ---
i18n-sync-crowdin:
  variables:
      I18N_SYNC_CROWDIN_PROJECT: 'apple-mail'
  extends: .i18n-sync-crowdin-shared-apple

i18n-commit-locales:
  variables:
      I18N_COMMIT_CROWDIN_PROJECT: 'apple-mail'
  extends: .i18n-commit-locales-shared-apple2

