configuration: Debug
input_format: profdata
xcodeproj: ProtonMail.xcodeproj
workspace: ProtonMail.xcworkspace
scheme: Tests
build_directory: ../test_output
binary_basename: ProtonMail
ignore: 
  - "Pods/*"